{"name": "test_failed_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'PurchaseWorkflow' object has no attribute 'result'", "trace": "fixturefunc = <function verify_error_message at 0x11176b7e0>\nrequest = <FixtureRequest for <Function test_failed_login>>\nkwargs = {'purchase_workflow': <workflows.purchase_workflow.PurchaseWorkflow object at 0x1116fb8c0>}\n\n    def call_fixture_func(\n        fixturefunc: _FixtureFunc[FixtureValue], request: FixtureRequest, kwargs\n    ) -> FixtureValue:\n        if inspect.isgeneratorfunction(fixturefunc):\n            fixturefunc = cast(Callable[..., Generator[FixtureValue]], fixturefunc)\n            generator = fixturefunc(**kwargs)\n            try:\n                fixture_result = next(generator)\n            except StopIteration:\n                raise ValueError(f\"{request.fixturename} did not yield a value\") from None\n            finalizer = functools.partial(_teardown_yield_fixture, fixturefunc, generator)\n            request.addfinalizer(finalizer)\n        else:\n            fixturefunc = cast(Callable[..., FixtureValue], fixturefunc)\n>           fixture_result = fixturefunc(**kwargs)\n                             ^^^^^^^^^^^^^^^^^^^^^\n\n.venv/lib/python3.13/site-packages/_pytest/fixtures.py:930: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\npurchase_workflow = <workflows.purchase_workflow.PurchaseWorkflow object at 0x1116fb8c0>\n\n    @allure.step('Error message \"{message}\"')\n    @then(\"I should see an error message\")\n    def verify_error_message(purchase_workflow):\n        # 验证错误消息\n>       assert \"Error\" in purchase_workflow.result\n                          ^^^^^^^^^^^^^^^^^^^^^^^^\nE       AttributeError: 'PurchaseWorkflow' object has no attribute 'result'\n\ntests/steps/test_purchase_steps.py:48: AttributeError"}, "description": "../features/login.feature: Failed login with invalid credentials", "start": 1759213064453, "stop": 1759213064757, "uuid": "042429a3-cfea-4895-8271-1bdd7402d3ab", "historyId": "eb98303b78b0dd8a81a7d4c9688110a7", "testCaseId": "eb98303b78b0dd8a81a7d4c9688110a7", "fullName": "tests.test_login#test_failed_login", "labels": [{"name": "feature", "value": "Login flow"}, {"name": "story", "value": "2.Failed login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "MacBookPro"}, {"name": "thread", "value": "2930-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}