{"name": "test_failed_login", "status": "passed", "description": "../fixtures/login.feature: Failed login with invalid credentials", "start": 1758082366902, "stop": 1758082367198, "uuid": "b29ec31b-148b-421d-910a-5113d1b4e0b0", "historyId": "eb98303b78b0dd8a81a7d4c9688110a7", "testCaseId": "eb98303b78b0dd8a81a7d4c9688110a7", "fullName": "tests.test_login#test_failed_login", "labels": [{"name": "feature", "value": "Login flow"}, {"name": "story", "value": "2.Failed login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "MacBookPro"}, {"name": "thread", "value": "7058-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}], "titlePath": ["tests", "test_login.py"]}